name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
  - cron: '20 12 * * *'
  #- cron: '0 3 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.7.1
        with:
          audit_level: moderate
          github_token: ${{ secrets.VERY_HIDDEN_ONLY_HERE_SECRET }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
