name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
  #schedule:
    #- cron: '0 3 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.1
      - name: install dependencies
        run: npm install #npm ci enough if package-lock exists
      - name: perform audit
        run: npm audit
